### PR TITLE
Added script and randomized  tagline of the page

### LINKED ISSUE #5: [Feature Request]: Make the tagline of the page randomize...
image

The Original Website's Tagline in the heading is random and changes on every reload,

We need to implement this randomized tagline feature using JavaScript.

### PR DESCRIPTION
**Pull request by Chanpreetk03**
## Description

Randomized the tagline of the clone using external Java-Script

## Issue Resolved

#5 

Before the tagline in the heading was hard-coded and displayed only one of them which was not the case in the original site. 
 So, using basic JS I randomized the taglines appearing.

## Screenshots 

Before:
image

After:
One example:
image

Another:
image

## Checklist

Please make sure to review the following before submitting your PR: 

- [x] I have read the [contribution guidelines](https://github.com/PEC-CSS/MovieDroid/blob/main/CONTRIBUTING.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

### CODE REVIEW

**Review by Manobal-Singh-Bagady — APPROVED** [review]
Good Work, @Chanpreetk03, Looks Good to me.

**Comment by Manobal-Singh-Bagady** [comment]
To make a minor correction, @Chanpreetk03 always mentions the issue this pull request refers to in the PR's description. I have edited the description. Take this in mind next time.

**Review by Manobal-Singh-Bagady — CHANGES_REQUESTED** [review]
There are conflicts in the merge. Your fork is not in sync with the main branch @Chanpreetk03. Please sync that so that I can merge the PR.

**Comment by Chanpreetk03** [comment]
> There are conflicts in the merge. Your fork is not in sync with the main branch @Chanpreetk03. Please sync that so that I can merge the PR.

Synced the fork and made the required changes.

**Review by Manobal-Singh-Bagady — APPROVED** [review]
Good Work, @Chanpreetk03. The Conflicts have been resolved. 💯

**Comment by Manobal-Singh-Bagady** [comment]
I am merging the PR. GW @Chanpreetk03. Congratulation on your first contribution. 💯 🥇 🥳

**Pull request merged**
