### PR TITLE
Added links to the companies.

### LINKED ISSUE #8: [Bug]: The links to the companies do not go anywhere.
image

We need to add links to the company websites, like the original git-scm's page.

### PR DESCRIPTION
**Pull request by Nikhil7174**
## Description

Added links to the companies

## Issue Resolved

Fixes #8

## Checklist

Please make sure to review the following before submitting your PR: 

- [x] I have read the [contribution guidelines](https://github.com/MSB-s-Projects/Git-scm-Clone/blob/main/docs/CONTRIBUTING.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

### CODE REVIEW

**Review by Manobal-Singh-Bagady — CHANGES_REQUESTED** [review]
@Nikhil7174 in the original Git website, the links to the companies point to their GitHub organizations. not their websites. Please change that and make it similar to https://git-scm.com/

Also this issue is already being worked on by @Astha-Raghuwanshi.

**Comment by Nikhil7174** [comment]
@Manobal-Singh-Bagady Changed the links. I did not saw anyone assigned this issue in the issue page when i had created a pull request. You can assign @Astha-Raghuwanshi this issue if you want.

**Review by Manobal-Singh-Bagady — APPROVED** [review]
LGTM @Nikhil7174

**Comment by Manobal-Singh-Bagady** [comment]
GW @Nikhil7174 merging the PR.

**Pull request merged**
